/**
 * @fileoverview constants.ts
 *
 * Game balance constants and hardcoded reel strips.
 *
 * The reel strips match the exact probability distribution of the RNG:
 * Ten=45%, Jack=10%, Queen=20%, King=13%, Ace=9%, Wild=2%, Bonus=1%.
 *
 * To regenerate strips after changing grid config:
 *   pnpm --filter @lucky-slots/engine update-strips
 */

/** RNG threshold boundaries (0–999). A symbol is chosen when rng < its threshold. */
export const THRESHOLDS = {
  ten: 450,
  jack: 550,
  queen: 750,
  king: 880,
  ace: 970,
  wild: 990,
  bonus: 999,
} as const;

/** Available bet amounts in ascending order. */
export const BET_AMOUNTS = [0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000] as const;

/** Starting balance for new players. */
export const DEFAULT_BALANCE = 1000.0;

/** Default bet on first login. */
export const DEFAULT_BET = 0.1;

/**
 * Payout multipliers for each (size, symbol) combination.
 *
 * Key format: "{size} {SymbolName}" (e.g. "5 Ace").
 * These values are summed when multiple paylines hit in a single spin.
 */
const HARDCODED_MULTIPLIERS: Record<string, number> = {
  '3 Ten': 0.25,
  '4 Ten': 1,
  '5 Ten': 5,
  '3 Jack': 0.5,
  '4 Jack': 2,
  '5 Jack': 10,
  '3 Queen': 1,
  '4 Queen': 4,
  '5 Queen': 20,
  '3 King': 2,
  '4 King': 8,
  '5 King': 40,
  '3 Ace': 4,
  '4 Ace': 12,
  '5 Ace': 56,
};

/**
 * Extrapolation factor used when a multiplier is missing from the hardcoded table.
 * Each additional symbol in a payline roughly quadruples the payout.
 */
const EXTRAPOLATION_FACTOR = 4;

const computedCache = new Map<string, number>();
const autoGeneratedKeys = new Set<string>();

/**
 * Look up a multiplier, auto-computing missing values.
 *
 * If a (size, symbol) combination is not in the hardcoded table, the engine
 * extrapolates from the closest known value using a ×4 progression. This makes
 * the multiplier table self-repairing — switching grid sizes never breaks payouts.
 *
 * @param size   Path length (number of contiguous symbols)
 * @param symbol Title-case symbol name (e.g. "Ace", "Ten")
 * @returns      Multiplier value (≥ 0)
 */
export function getMultiplier(size: number, symbol: string): number {
  const key = `${size} ${symbol}`;

  const cached = computedCache.get(key);
  if (cached !== undefined) return cached;

  const hardcoded = HARDCODED_MULTIPLIERS[key];
  if (hardcoded !== undefined) {
    computedCache.set(key, hardcoded);
    return hardcoded;
  }

  // Find all known sizes for this symbol
  const knownEntries: { size: number; value: number }[] = [];
  for (const [k, v] of Object.entries(HARDCODED_MULTIPLIERS)) {
    const m = k.match(/^(\d+)\s+(.+)$/);
    if (m && m[2] === symbol) {
      knownEntries.push({ size: parseInt(m[1], 10), value: v });
    }
  }

  let result: number;

  if (knownEntries.length === 0) {
    // No data at all for this symbol — use a tiny safe default
    result = 0.1;
  } else {
    knownEntries.sort((a, b) => a.size - b.size);

    const smallest = knownEntries[0];
    const largest = knownEntries[knownEntries.length - 1];

    if (size <= smallest.size) {
      // Extrapolate downward
      const steps = smallest.size - size;
      result = smallest.value / Math.pow(EXTRAPOLATION_FACTOR, steps);
    } else if (size >= largest.size) {
      // Extrapolate upward
      const steps = size - largest.size;
      result = largest.value * Math.pow(EXTRAPOLATION_FACTOR, steps);
    } else {
      // Interpolate between two known values
      let lower = smallest;
      let upper = largest;
      for (let i = 0; i < knownEntries.length - 1; i++) {
        if (knownEntries[i].size <= size && knownEntries[i + 1].size >= size) {
          lower = knownEntries[i];
          upper = knownEntries[i + 1];
          break;
        }
      }
      const t = (size - lower.size) / (upper.size - lower.size);
      result = lower.value + t * (upper.value - lower.value);
    }
  }

  computedCache.set(key, result);
  if (!autoGeneratedKeys.has(key)) {
    autoGeneratedKeys.add(key);
  }
  return result;
}

/**
 * Return a list of all auto-generated multiplier keys for this session.
 * Useful for logging or alerting game designers that the table needs updating.
 */
export function getAutoGeneratedMultipliers(): string[] {
  return Array.from(autoGeneratedKeys);
}

/**
 * Legacy direct-access multiplier table.
 *
 * Prefer {@link getMultiplier} for new code — it auto-computes missing values.
 */
export const MULTIPLIERS: Record<string, number> = { ...HARDCODED_MULTIPLIERS };

// <AUTO-GENERATED-REEL-STRIPS>
// This section is automatically regenerated by `pnpm update-strips`.
// Do not edit manually.
export const REEL_STRIPS: string[][] = [
  // Reel 1
  [
    'JACK','TEN','TEN','QUEEN','KING','JACK','TEN','ACE','JACK','JACK',
    'JACK','TEN','QUEEN','QUEEN','QUEEN','QUEEN','TEN','TEN','TEN','TEN',
    'QUEEN','KING','JACK','TEN','TEN','QUEEN','TEN','TEN','KING','QUEEN',
    'QUEEN','JACK','TEN','KING','TEN','QUEEN','TEN','KING','TEN','KING',
    'QUEEN','TEN','TEN','TEN','TEN','TEN','ACE','ACE','TEN','QUEEN',
    'QUEEN','ACE','KING','TEN','TEN','KING','QUEEN','KING','KING','TEN',
    'TEN','TEN','ACE','ACE','WILD','QUEEN','KING','TEN','BONUS','TEN',
    'TEN','ACE','TEN','QUEEN','ACE','TEN','TEN','QUEEN','QUEEN','TEN',
    'QUEEN','TEN','TEN','TEN','KING','TEN','TEN','KING','WILD','TEN',
    'TEN','JACK','JACK','ACE','TEN','TEN','TEN','QUEEN','JACK','TEN'
  ],
  // Reel 2
  [
    'QUEEN','KING','JACK','TEN','TEN','TEN','TEN','QUEEN','QUEEN','QUEEN',
    'ACE','QUEEN','JACK','TEN','TEN','TEN','QUEEN','TEN','JACK','TEN',
    'JACK','TEN','TEN','TEN','TEN','JACK','JACK','KING','TEN','QUEEN',
    'TEN','QUEEN','KING','TEN','QUEEN','TEN','WILD','ACE','KING','TEN',
    'TEN','QUEEN','KING','TEN','ACE','TEN','QUEEN','QUEEN','TEN','JACK',
    'KING','QUEEN','KING','KING','TEN','KING','TEN','TEN','TEN','TEN',
    'QUEEN','TEN','TEN','TEN','TEN','TEN','ACE','ACE','JACK','QUEEN',
    'TEN','QUEEN','TEN','KING','JACK','ACE','BONUS','KING','TEN','KING',
    'ACE','ACE','TEN','QUEEN','QUEEN','TEN','TEN','WILD','TEN','TEN',
    'ACE','TEN','TEN','TEN','TEN','KING','QUEEN','JACK','QUEEN','TEN'
  ],
  // Reel 3
  [
    'TEN','ACE','KING','QUEEN','TEN','KING','TEN','TEN','TEN','TEN',
    'QUEEN','TEN','QUEEN','QUEEN','TEN','QUEEN','TEN','TEN','TEN','TEN',
    'TEN','ACE','QUEEN','TEN','JACK','ACE','KING','QUEEN','KING','TEN',
    'TEN','JACK','TEN','WILD','QUEEN','KING','TEN','TEN','TEN','TEN',
    'TEN','JACK','WILD','QUEEN','TEN','QUEEN','QUEEN','TEN','BONUS','TEN',
    'JACK','JACK','KING','ACE','TEN','QUEEN','TEN','JACK','QUEEN','JACK',
    'TEN','QUEEN','KING','JACK','KING','TEN','TEN','QUEEN','TEN','QUEEN',
    'ACE','TEN','QUEEN','TEN','TEN','ACE','QUEEN','ACE','ACE','TEN',
    'ACE','QUEEN','TEN','TEN','TEN','TEN','JACK','JACK','KING','KING',
    'TEN','KING','KING','TEN','QUEEN','TEN','TEN','TEN','KING','TEN'
  ],
  // Reel 4
  [
    'QUEEN','QUEEN','TEN','QUEEN','JACK','QUEEN','KING','TEN','JACK','TEN',
    'QUEEN','TEN','ACE','TEN','TEN','TEN','TEN','TEN','QUEEN','TEN',
    'TEN','KING','KING','WILD','TEN','TEN','TEN','QUEEN','KING','TEN',
    'KING','QUEEN','KING','JACK','TEN','QUEEN','TEN','QUEEN','TEN','KING',
    'QUEEN','TEN','KING','QUEEN','QUEEN','QUEEN','QUEEN','ACE','JACK','TEN',
    'TEN','JACK','TEN','TEN','TEN','TEN','KING','TEN','TEN','TEN',
    'TEN','TEN','TEN','TEN','JACK','TEN','TEN','QUEEN','ACE','QUEEN',
    'KING','ACE','TEN','ACE','JACK','ACE','QUEEN','TEN','KING','ACE',
    'WILD','TEN','TEN','TEN','QUEEN','KING','JACK','TEN','TEN','TEN',
    'TEN','JACK','JACK','TEN','KING','ACE','QUEEN','BONUS','ACE','TEN'
  ],
  // Reel 5
  [
    'TEN','TEN','JACK','QUEEN','ACE','TEN','KING','QUEEN','QUEEN','KING',
    'TEN','TEN','QUEEN','KING','QUEEN','ACE','QUEEN','TEN','ACE','TEN',
    'KING','TEN','TEN','QUEEN','TEN','QUEEN','TEN','TEN','KING','BONUS',
    'TEN','KING','QUEEN','TEN','TEN','TEN','KING','KING','TEN','ACE',
    'TEN','TEN','QUEEN','ACE','KING','TEN','TEN','JACK','JACK','QUEEN',
    'TEN','TEN','QUEEN','TEN','KING','JACK','TEN','TEN','TEN','ACE',
    'JACK','TEN','JACK','QUEEN','KING','QUEEN','TEN','QUEEN','TEN','KING',
    'TEN','ACE','WILD','WILD','TEN','QUEEN','QUEEN','TEN','JACK','TEN',
    'ACE','JACK','TEN','QUEEN','TEN','TEN','JACK','TEN','KING','QUEEN',
    'ACE','TEN','TEN','TEN','TEN','JACK','TEN','QUEEN','TEN','TEN'
  ],
  // Reel 6
  [
    'ACE','ACE','WILD','TEN','KING','TEN','QUEEN','ACE','ACE','TEN',
    'KING','KING','TEN','TEN','JACK','TEN','TEN','QUEEN','TEN','WILD',
    'KING','TEN','TEN','TEN','QUEEN','QUEEN','TEN','BONUS','KING','QUEEN',
    'TEN','TEN','JACK','TEN','TEN','TEN','QUEEN','KING','QUEEN','TEN',
    'QUEEN','JACK','JACK','TEN','QUEEN','TEN','TEN','TEN','QUEEN','KING',
    'TEN','TEN','KING','TEN','QUEEN','QUEEN','QUEEN','QUEEN','QUEEN','ACE',
    'TEN','TEN','TEN','JACK','ACE','QUEEN','TEN','TEN','ACE','KING',
    'QUEEN','TEN','KING','TEN','QUEEN','QUEEN','QUEEN','ACE','TEN','JACK',
    'TEN','TEN','TEN','JACK','KING','TEN','JACK','TEN','TEN','TEN',
    'ACE','KING','KING','TEN','TEN','TEN','JACK','JACK','TEN','TEN'
  ]
];
// </AUTO-GENERATED-REEL-STRIPS>
