/**
 * @fileoverview constants.ts
 *
 * Game balance constants and hardcoded reel strips.
 *
 * Reel strips and multipliers are the single source of truth for symbol
 * generation and payouts. To regenerate strips or rebalance RTP:
 *   pnpm --filter @lucky-slots/engine optimize-strips
 *
 * To regenerate random strips from the base distribution:
 *   pnpm --filter @lucky-slots/engine update-strips
 */

/** Available bet amounts in ascending order. */
export const BET_AMOUNTS = [0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000] as const;

/** Starting balance for new players. */
export const DEFAULT_BALANCE = 1000.0;

/** Default bet on first login. */
export const DEFAULT_BET = 0.1;

/**
 * Payout multipliers for each (size, symbol) combination.
 *
 * Key format: "{size} {SymbolName}" (e.g. "4 Ace").
 * These values are summed when multiple paylines hit in a single spin.
 *
 * Current balance target (via `pnpm optimize-strips`):
 *   Grid: 4×4, minMatch=4, stripSize=100
 *   Target RTP:       95.0%
 *   Target Hit-Rate:  20.0%
 *
 * Size-4 multipliers below were scaled by the ReelOptimizer to hit the
 * 95% RTP target given the current asymmetric reel strips. Size-3 entries
 * are unused with minMatch=4 but kept for backward compatibility / future
 * grid-size changes (extrapolation will derive from them).
 *
 * ┌─────────┬────────┬────────────────────────────────────────┐
 * │ Combo   │ Mult   │ Notes                                  │
 * ├─────────┼────────┼────────────────────────────────────────┤
 * │ 3 Ten   │ 0.2500 │ Base low-value hit (unused @ minMatch=4) │
 * │ 4 Ten   │ 0.1924 │ Scaled by optimizer for 95% RTP target │
 * │ 5 Ten   │ 5.0000 │ Kept for future 5× grids               │
 * │ 3 Jack  │ 0.5000 │ Base medium-value hit (unused)         │
 * │ 4 Jack  │ 0.7713 │ Scaled by optimizer for 95% RTP target │
 * │ 5 Jack  │ 10.0000│ Kept for future 5× grids               │
 * │ 3 Queen │ 1.0000 │ Base medium-value hit (unused)         │
 * │ 4 Queen │ 1.8995 │ Scaled by optimizer for 95% RTP target │
 * │ 5 Queen │ 20.0000│ Kept for future 5× grids               │
 * │ 3 King  │ 2.0000 │ Base high-value hit (unused)           │
 * │ 4 King  │ 1.2746 │ Scaled by optimizer for 95% RTP target │
 * │ 5 King  │ 40.0000│ Kept for future 5× grids               │
 * │ 3 Ace   │ 4.0000 │ Base top-value hit (unused)            │
 * │ 4 Ace   │ 1.0967 │ Scaled by optimizer for 95% RTP target │
 * │ 5 Ace   │ 56.0000│ Kept for future 5× grids               │
 * └─────────┴────────┴────────────────────────────────────────┘
 */
const HARDCODED_MULTIPLIERS: Record<string, number> = {
  '3 Ace': 4.0000,
  '3 Jack': 0.5000,
  '3 King': 2.0000,
  '3 Queen': 1.0000,
  '3 Ten': 0.2500,
  '4 Ace': 1.3989,
  '4 Jack': 1.1314,
  '4 King': 1.3820,
  '4 Queen': 2.4229,
  '4 Ten': 0.2454,
  '5 Ace': 56.0000,
  '5 Jack': 10.0000,
  '5 King': 40.0000,
  '5 Queen': 20.0000,
  '5 Ten': 5.0000,
};

/**
 * Extrapolation factor used when a multiplier is missing from the hardcoded table.
 * Each additional symbol in a payline roughly quadruples the payout.
 */
const EXTRAPOLATION_FACTOR = 4;

const computedCache = new Map<string, number>();
const autoGeneratedKeys = new Set<string>();

/**
 * Look up a multiplier, auto-computing missing values.
 *
 * If a (size, symbol) combination is not in the hardcoded table, the engine
 * extrapolates from the closest known value using a ×4 progression. This makes
 * the multiplier table self-repairing — switching grid sizes never breaks payouts.
 *
 * @param size   Path length (number of contiguous symbols)
 * @param symbol Title-case symbol name (e.g. "Ace", "Ten")
 * @returns      Multiplier value (≥ 0)
 */
export function getMultiplier(size: number, symbol: string): number {
  const key = `${size} ${symbol}`;

  const cached = computedCache.get(key);
  if (cached !== undefined) return cached;

  const hardcoded = HARDCODED_MULTIPLIERS[key];
  if (hardcoded !== undefined) {
    computedCache.set(key, hardcoded);
    return hardcoded;
  }

  // Find all known sizes for this symbol
  const knownEntries: { size: number; value: number }[] = [];
  for (const [k, v] of Object.entries(HARDCODED_MULTIPLIERS)) {
    const m = k.match(/^(\d+)\s+(.+)$/);
    if (m && m[2] === symbol) {
      knownEntries.push({ size: parseInt(m[1], 10), value: v });
    }
  }

  let result: number;

  if (knownEntries.length === 0) {
    // No data at all for this symbol — use a tiny safe default
    result = 0.1;
  } else {
    knownEntries.sort((a, b) => a.size - b.size);

    const smallest = knownEntries[0];
    const largest = knownEntries[knownEntries.length - 1];

    if (size <= smallest.size) {
      // Extrapolate downward
      const steps = smallest.size - size;
      result = smallest.value / Math.pow(EXTRAPOLATION_FACTOR, steps);
    } else if (size >= largest.size) {
      // Extrapolate upward
      const steps = size - largest.size;
      result = largest.value * Math.pow(EXTRAPOLATION_FACTOR, steps);
    } else {
      // Interpolate between two known values
      let lower = smallest;
      let upper = largest;
      for (let i = 0; i < knownEntries.length - 1; i++) {
        if (knownEntries[i].size <= size && knownEntries[i + 1].size >= size) {
          lower = knownEntries[i];
          upper = knownEntries[i + 1];
          break;
        }
      }
      const t = (size - lower.size) / (upper.size - lower.size);
      result = lower.value + t * (upper.value - lower.value);
    }
  }

  computedCache.set(key, result);
  if (!autoGeneratedKeys.has(key)) {
    autoGeneratedKeys.add(key);
  }
  return result;
}

/**
 * Return a list of all auto-generated multiplier keys for this session.
 * Useful for logging or alerting game designers that the table needs updating.
 */
export function getAutoGeneratedMultipliers(): string[] {
  return Array.from(autoGeneratedKeys);
}

/**
 * Legacy direct-access multiplier table.
 *
 * Prefer {@link getMultiplier} for new code — it auto-computes missing values.
 */
export const MULTIPLIERS: Record<string, number> = { ...HARDCODED_MULTIPLIERS };

// <AUTO-GENERATED-REEL-STRIPS>
// This section is automatically regenerated by `pnpm update-strips`.
// Do not edit manually.
export const REEL_STRIPS: string[][] = [
  // Reel 1
  [
    'KING','TEN','TEN','QUEEN','KING','TEN','QUEEN','TEN','WILD','TEN',
    'QUEEN','QUEEN','TEN','TEN','TEN','TEN','WILD','TEN','KING','QUEEN',
    'JACK','QUEEN','KING','JACK','TEN','QUEEN','QUEEN','JACK','JACK','TEN',
    'TEN','KING','TEN','TEN','TEN','QUEEN','TEN','TEN','TEN','KING',
    'KING','TEN','QUEEN','QUEEN','JACK','QUEEN','TEN','TEN','KING','KING',
    'QUEEN','TEN','JACK','QUEEN','JACK','TEN','QUEEN','TEN','KING','JACK',
    'TEN','KING','QUEEN','TEN','TEN','TEN','QUEEN','JACK','TEN','TEN',
    'TEN','QUEEN','TEN','TEN','TEN','TEN','QUEEN','KING','QUEEN','QUEEN',
    'QUEEN','QUEEN','TEN','JACK','TEN','QUEEN','KING','KING','KING','JACK',
    'KING','TEN','QUEEN','TEN','TEN','JACK','KING','JACK','TEN','TEN'
  ],
  // Reel 2
  [
    'KING','JACK','TEN','KING','QUEEN','KING','QUEEN','KING','KING','KING',
    'KING','KING','KING','KING','KING','KING','QUEEN','JACK','JACK','KING',
    'JACK','JACK','JACK','JACK','QUEEN','QUEEN','QUEEN','QUEEN','KING','JACK',
    'JACK','QUEEN','KING','QUEEN','JACK','QUEEN','QUEEN','KING','KING','JACK',
    'JACK','KING','QUEEN','QUEEN','QUEEN','JACK','QUEEN','JACK','ACE','QUEEN',
    'JACK','JACK','QUEEN','QUEEN','JACK','KING','JACK','ACE','WILD','KING',
    'QUEEN','ACE','KING','QUEEN','JACK','QUEEN','KING','JACK','KING','JACK',
    'JACK','KING','JACK','JACK','JACK','KING','JACK','JACK','KING','JACK',
    'QUEEN','JACK','QUEEN','ACE','JACK','QUEEN','QUEEN','QUEEN','JACK','ACE',
    'QUEEN','ACE','KING','ACE','QUEEN','ACE','TEN','KING','WILD','KING'
  ],
  // Reel 3
  [
    'QUEEN','QUEEN','QUEEN','JACK','TEN','JACK','TEN','JACK','TEN','QUEEN',
    'TEN','ACE','QUEEN','TEN','QUEEN','TEN','QUEEN','TEN','JACK','KING',
    'ACE','JACK','QUEEN','TEN','JACK','ACE','QUEEN','JACK','KING','JACK',
    'TEN','QUEEN','QUEEN','KING','QUEEN','TEN','QUEEN','KING','QUEEN','TEN',
    'JACK','ACE','ACE','QUEEN','KING','TEN','TEN','TEN','TEN','JACK',
    'KING','WILD','JACK','ACE','TEN','KING','ACE','TEN','QUEEN','KING',
    'JACK','ACE','QUEEN','TEN','TEN','KING','QUEEN','QUEEN','KING','TEN',
    'WILD','QUEEN','TEN','TEN','TEN','TEN','TEN','QUEEN','TEN','JACK',
    'JACK','KING','QUEEN','TEN','KING','QUEEN','KING','QUEEN','TEN','TEN',
    'TEN','TEN','TEN','QUEEN','JACK','TEN','QUEEN','JACK','QUEEN','TEN'
  ],
  // Reel 4
  [
    'ACE','TEN','ACE','TEN','ACE','ACE','ACE','ACE','ACE','ACE',
    'ACE','TEN','TEN','TEN','TEN','TEN','TEN','TEN','TEN','TEN',
    'TEN','TEN','TEN','TEN','TEN','ACE','TEN','TEN','TEN','ACE',
    'TEN','TEN','TEN','TEN','TEN','TEN','TEN','TEN','TEN','TEN',
    'TEN','TEN','TEN','TEN','TEN','KING','QUEEN','ACE','QUEEN','TEN',
    'TEN','QUEEN','TEN','TEN','QUEEN','QUEEN','TEN','ACE','QUEEN','QUEEN',
    'QUEEN','TEN','TEN','TEN','TEN','QUEEN','TEN','WILD','WILD','TEN',
    'ACE','TEN','QUEEN','QUEEN','TEN','QUEEN','TEN','TEN','TEN','TEN',
    'QUEEN','TEN','QUEEN','TEN','QUEEN','QUEEN','TEN','QUEEN','ACE','TEN',
    'TEN','QUEEN','TEN','QUEEN','TEN','ACE','TEN','TEN','TEN','QUEEN'
  ]
];
// </AUTO-GENERATED-REEL-STRIPS>
