export const THRESHOLDS = {
  ten: 450,
  jack: 550,
  queen: 750,
  king: 880,
  ace: 970,
  wild: 990,
  bonus: 999,
} as const;

export const BET_AMOUNTS = [0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000] as const;

export const DEFAULT_BALANCE = 1000.0;
export const DEFAULT_BET = 0.1;

export const MULTIPLIERS: Record<string, number> = {
  '3 Ten': 0.25,
  '4 Ten': 1,
  '5 Ten': 5,
  '3 Jack': 0.5,
  '4 Jack': 2,
  '5 Jack': 10,
  '3 Queen': 1,
  '4 Queen': 4,
  '5 Queen': 20,
  '3 King': 2,
  '4 King': 8,
  '5 King': 40,
  '3 Ace': 4,
  '4 Ace': 12,
  '5 Ace': 56,
};

// Hardcoded reel strips (100 symbols each) matching RNG distribution exactly.
// Generated by scripts/generateReelStrips.ts — run `npx tsx scripts/generateReelStrips.ts` to regenerate.
// Counts: Ten=45, Jack=10, Queen=20, King=13, Ace=9, Wild=2, Bonus=1
export const REEL_STRIPS: string[][] = [
  // Reel 1
  [
    'JACK','TEN','TEN','QUEEN','KING','JACK','TEN','ACE','JACK','JACK',
    'JACK','TEN','QUEEN','QUEEN','QUEEN','QUEEN','TEN','TEN','TEN','TEN',
    'QUEEN','KING','JACK','TEN','TEN','QUEEN','TEN','TEN','KING','QUEEN',
    'QUEEN','JACK','TEN','KING','TEN','QUEEN','TEN','KING','TEN','KING',
    'QUEEN','TEN','TEN','TEN','TEN','TEN','ACE','ACE','TEN','QUEEN',
    'QUEEN','ACE','KING','TEN','TEN','KING','QUEEN','KING','KING','TEN',
    'TEN','TEN','ACE','ACE','WILD','QUEEN','KING','TEN','BONUS','TEN',
    'TEN','ACE','TEN','QUEEN','ACE','TEN','TEN','QUEEN','QUEEN','TEN',
    'QUEEN','TEN','TEN','TEN','KING','TEN','TEN','KING','WILD','TEN',
    'TEN','JACK','JACK','ACE','TEN','TEN','TEN','QUEEN','JACK','TEN'
  ],
  // Reel 2
  [
    'QUEEN','KING','JACK','TEN','TEN','TEN','TEN','QUEEN','QUEEN','QUEEN',
    'ACE','QUEEN','JACK','TEN','TEN','TEN','QUEEN','TEN','JACK','TEN',
    'JACK','TEN','TEN','TEN','TEN','JACK','JACK','KING','TEN','QUEEN',
    'TEN','QUEEN','KING','TEN','QUEEN','TEN','WILD','ACE','KING','TEN',
    'TEN','QUEEN','KING','TEN','ACE','TEN','QUEEN','QUEEN','TEN','JACK',
    'KING','QUEEN','KING','KING','TEN','KING','TEN','TEN','TEN','TEN',
    'QUEEN','TEN','TEN','TEN','TEN','TEN','ACE','ACE','JACK','QUEEN',
    'TEN','QUEEN','TEN','KING','JACK','ACE','BONUS','KING','TEN','KING',
    'ACE','ACE','TEN','QUEEN','QUEEN','TEN','TEN','WILD','TEN','TEN',
    'ACE','TEN','TEN','TEN','TEN','KING','QUEEN','JACK','QUEEN','TEN'
  ],
  // Reel 3
  [
    'TEN','ACE','KING','QUEEN','TEN','KING','TEN','TEN','TEN','TEN',
    'QUEEN','TEN','QUEEN','QUEEN','TEN','QUEEN','TEN','TEN','TEN','TEN',
    'TEN','ACE','QUEEN','TEN','JACK','ACE','KING','QUEEN','KING','TEN',
    'TEN','JACK','TEN','WILD','QUEEN','KING','TEN','TEN','TEN','TEN',
    'TEN','JACK','WILD','QUEEN','TEN','QUEEN','QUEEN','TEN','BONUS','TEN',
    'JACK','JACK','KING','ACE','TEN','QUEEN','TEN','JACK','QUEEN','JACK',
    'TEN','QUEEN','KING','JACK','KING','TEN','TEN','QUEEN','TEN','QUEEN',
    'ACE','TEN','QUEEN','TEN','TEN','ACE','QUEEN','ACE','ACE','TEN',
    'ACE','QUEEN','TEN','TEN','TEN','TEN','JACK','JACK','KING','KING',
    'TEN','KING','KING','TEN','QUEEN','TEN','TEN','TEN','KING','TEN'
  ],
  // Reel 4
  [
    'QUEEN','QUEEN','TEN','QUEEN','JACK','QUEEN','KING','TEN','JACK','TEN',
    'QUEEN','TEN','ACE','TEN','TEN','TEN','TEN','TEN','QUEEN','TEN',
    'TEN','KING','KING','WILD','TEN','TEN','TEN','QUEEN','KING','TEN',
    'KING','QUEEN','KING','JACK','TEN','QUEEN','TEN','QUEEN','TEN','KING',
    'QUEEN','TEN','KING','QUEEN','QUEEN','QUEEN','QUEEN','ACE','JACK','TEN',
    'TEN','JACK','TEN','TEN','TEN','TEN','KING','TEN','TEN','TEN',
    'TEN','TEN','TEN','TEN','JACK','TEN','TEN','QUEEN','ACE','QUEEN',
    'KING','ACE','TEN','ACE','JACK','ACE','QUEEN','TEN','KING','ACE',
    'WILD','TEN','TEN','TEN','QUEEN','KING','JACK','TEN','TEN','TEN',
    'TEN','JACK','JACK','TEN','KING','ACE','QUEEN','BONUS','ACE','TEN'
  ],
  // Reel 5
  [
    'TEN','TEN','JACK','QUEEN','ACE','TEN','KING','QUEEN','QUEEN','KING',
    'TEN','TEN','QUEEN','KING','QUEEN','ACE','QUEEN','TEN','ACE','TEN',
    'KING','TEN','TEN','QUEEN','TEN','QUEEN','TEN','TEN','KING','BONUS',
    'TEN','KING','QUEEN','TEN','TEN','TEN','KING','KING','TEN','ACE',
    'TEN','TEN','QUEEN','ACE','KING','TEN','TEN','JACK','JACK','QUEEN',
    'TEN','TEN','QUEEN','TEN','KING','JACK','TEN','TEN','TEN','ACE',
    'JACK','TEN','JACK','QUEEN','KING','QUEEN','TEN','QUEEN','TEN','KING',
    'TEN','ACE','WILD','WILD','TEN','QUEEN','QUEEN','TEN','JACK','TEN',
    'ACE','JACK','TEN','QUEEN','TEN','TEN','JACK','TEN','KING','QUEEN',
    'ACE','TEN','TEN','TEN','TEN','JACK','TEN','QUEEN','TEN','TEN'
  ]
];
