import { describe, it, expect } from 'vitest';
import { getMultiplier, getAutoGeneratedMultipliers, MULTIPLIERS, BET_AMOUNTS, DEFAULT_BALANCE, DEFAULT_BET } from '../src/constants';

describe('constants', () => {
  describe('getMultiplier', () => {
    it('returns hardcoded values for known combinations', () => {
      // These exact values are set by the optimizer and may change after rebalancing.
      // We assert they are stable (cached) and match the exported MULTIPLIERS table.
      expect(getMultiplier(3, 'Ten')).toBe(MULTIPLIERS['3 Ten']);
      expect(getMultiplier(4, 'Ten')).toBe(MULTIPLIERS['4 Ten']);
      expect(getMultiplier(5, 'Ten')).toBe(MULTIPLIERS['5 Ten']);
      expect(getMultiplier(3, 'Ace')).toBe(MULTIPLIERS['3 Ace']);
      expect(getMultiplier(4, 'Ace')).toBe(MULTIPLIERS['4 Ace']);
      expect(getMultiplier(5, 'Ace')).toBe(MULTIPLIERS['5 Ace']);
    });

    it('returns the same value on repeated calls (caching)', () => {
      const a = getMultiplier(3, 'Queen');
      const b = getMultiplier(3, 'Queen');
      expect(a).toBe(b);
      expect(a).toBe(MULTIPLIERS['3 Queen']);
    });

    it('extrapolates upward using the extrapolation factor', () => {
      const base5Ten = MULTIPLIERS['5 Ten'] ?? 5;
      const base5Ace = MULTIPLIERS['5 Ace'] ?? 56;
      expect(getMultiplier(6, 'Ten')).toBe(base5Ten * 4);
      expect(getMultiplier(6, 'Ace')).toBe(base5Ace * 4);
    });

    it('extrapolates downward using the extrapolation factor', () => {
      const base3Ten = MULTIPLIERS['3 Ten'] ?? 0.25;
      const base3Ace = MULTIPLIERS['3 Ace'] ?? 4;
      expect(getMultiplier(2, 'Ten')).toBe(base3Ten / 4);
      expect(getMultiplier(2, 'Ace')).toBe(base3Ace / 4);
    });

    it('interpolates between two known values', () => {
      // 3 Queen and 5 Queen are hardcoded; 4 Queen should be exact if present.
      if ('4 Queen' in MULTIPLIERS) {
        expect(getMultiplier(4, 'Queen')).toBe(MULTIPLIERS['4 Queen']);
      }
    });

    it('falls back to 0.1 for completely unknown symbols', () => {
      expect(getMultiplier(3, 'UnknownSymbol')).toBe(0.1);
      expect(getMultiplier(5, 'AnotherUnknown')).toBe(0.1);
    });

    it('returns non-negative finite numbers for all valid sizes', () => {
      const symbols = ['Ten', 'Jack', 'Queen', 'King', 'Ace'];
      for (const sym of symbols) {
        for (let size = 1; size <= 10; size++) {
          const val = getMultiplier(size, sym);
          expect(typeof val).toBe('number');
          expect(val).toBeGreaterThanOrEqual(0);
          expect(Number.isFinite(val)).toBe(true);
        }
      }
    });
  });

  describe('getAutoGeneratedMultipliers', () => {
    it('returns an array', () => {
      const list = getAutoGeneratedMultipliers();
      expect(Array.isArray(list)).toBe(true);
    });

    it('includes keys that were auto-generated', () => {
      // Force an auto-generated lookup
      getMultiplier(10, 'Ten');
      const list = getAutoGeneratedMultipliers();
      expect(list.some((k) => k.startsWith('10 '))).toBe(true);
    });
  });

  describe('MULTIPLIERS', () => {
    it('contains the hardcoded multiplier entries', () => {
      expect(MULTIPLIERS['3 Ten']).toBeDefined();
      expect(MULTIPLIERS['5 Ace']).toBeDefined();
    });
  });

  describe('BET_AMOUNTS', () => {
    it('is strictly ascending', () => {
      for (let i = 1; i < BET_AMOUNTS.length; i++) {
        expect(BET_AMOUNTS[i]).toBeGreaterThan(BET_AMOUNTS[i - 1]);
      }
    });

    it('contains only positive numbers', () => {
      for (const amount of BET_AMOUNTS) {
        expect(amount).toBeGreaterThan(0);
      }
    });
  });

  describe('DEFAULT_BALANCE', () => {
    it('is a positive number', () => {
      expect(typeof DEFAULT_BALANCE).toBe('number');
      expect(DEFAULT_BALANCE).toBeGreaterThan(0);
    });
  });

  describe('DEFAULT_BET', () => {
    it('is one of the allowed bet amounts', () => {
      expect(BET_AMOUNTS.includes(DEFAULT_BET as (typeof BET_AMOUNTS)[number])).toBe(true);
    });
  });
});
