import { describe, it, expect } from 'vitest';
import { getMultiplier, getAutoGeneratedMultipliers, MULTIPLIERS, BET_AMOUNTS, DEFAULT_BALANCE, DEFAULT_BET } from '../src/constants';

describe('constants', () => {
  describe('getMultiplier', () => {
    it('returns hardcoded values for known combinations', () => {
      expect(getMultiplier(3, 'Ten')).toBe(0.25);
      expect(getMultiplier(4, 'Ten')).toBe(1);
      expect(getMultiplier(5, 'Ten')).toBe(5);
      expect(getMultiplier(3, 'Ace')).toBe(4);
      expect(getMultiplier(4, 'Ace')).toBe(12);
      expect(getMultiplier(5, 'Ace')).toBe(56);
    });

    it('returns the same value on repeated calls (caching)', () => {
      const a = getMultiplier(3, 'Queen');
      const b = getMultiplier(3, 'Queen');
      expect(a).toBe(b);
      expect(a).toBe(1);
    });

    it('extrapolates upward using the extrapolation factor', () => {
      // 5 Ten = 5, so 6 Ten should be 5 * 4 = 20
      expect(getMultiplier(6, 'Ten')).toBe(5 * 4);
      // 5 Ace = 56, so 6 Ace should be 56 * 4 = 224
      expect(getMultiplier(6, 'Ace')).toBe(56 * 4);
    });

    it('extrapolates downward using the extrapolation factor', () => {
      // 3 Ten = 0.25, so 2 Ten should be 0.25 / 4 = 0.0625
      expect(getMultiplier(2, 'Ten')).toBe(0.25 / 4);
      // 3 Ace = 4, so 2 Ace should be 4 / 4 = 1
      expect(getMultiplier(2, 'Ace')).toBe(1);
    });

    it('interpolates between two known values', () => {
      // 3 Queen = 1, 4 Queen = 4, 5 Queen = 20
      // For size 4.5 (not integer, but math still holds) we'd get 12,
      // but we only test integer sizes here. 4 is exact.
      expect(getMultiplier(4, 'Queen')).toBe(4);
    });

    it('falls back to 0.1 for completely unknown symbols', () => {
      expect(getMultiplier(3, 'UnknownSymbol')).toBe(0.1);
      expect(getMultiplier(5, 'AnotherUnknown')).toBe(0.1);
    });

    it('returns non-negative finite numbers for all valid sizes', () => {
      const symbols = ['Ten', 'Jack', 'Queen', 'King', 'Ace'];
      for (const sym of symbols) {
        for (let size = 1; size <= 10; size++) {
          const val = getMultiplier(size, sym);
          expect(typeof val).toBe('number');
          expect(val).toBeGreaterThanOrEqual(0);
          expect(Number.isFinite(val)).toBe(true);
        }
      }
    });
  });

  describe('getAutoGeneratedMultipliers', () => {
    it('returns an array', () => {
      const list = getAutoGeneratedMultipliers();
      expect(Array.isArray(list)).toBe(true);
    });

    it('includes keys that were auto-generated', () => {
      // Force an auto-generated lookup
      getMultiplier(10, 'Ten');
      const list = getAutoGeneratedMultipliers();
      expect(list.some((k) => k.startsWith('10 '))).toBe(true);
    });
  });

  describe('MULTIPLIERS', () => {
    it('contains the hardcoded multiplier entries', () => {
      expect(MULTIPLIERS['3 Ten']).toBe(0.25);
      expect(MULTIPLIERS['5 Ace']).toBe(56);
    });
  });

  describe('BET_AMOUNTS', () => {
    it('is strictly ascending', () => {
      for (let i = 1; i < BET_AMOUNTS.length; i++) {
        expect(BET_AMOUNTS[i]).toBeGreaterThan(BET_AMOUNTS[i - 1]);
      }
    });

    it('contains only positive numbers', () => {
      for (const amount of BET_AMOUNTS) {
        expect(amount).toBeGreaterThan(0);
      }
    });
  });

  describe('DEFAULT_BALANCE', () => {
    it('is a positive number', () => {
      expect(typeof DEFAULT_BALANCE).toBe('number');
      expect(DEFAULT_BALANCE).toBeGreaterThan(0);
    });
  });

  describe('DEFAULT_BET', () => {
    it('is one of the allowed bet amounts', () => {
      expect(BET_AMOUNTS.includes(DEFAULT_BET as (typeof BET_AMOUNTS)[number])).toBe(true);
    });
  });
});
