#!/usr/bin/env tsx
/**
 * @fileoverview optimizeStrips.ts
 *
 * Stand-alone CLI that runs the ReelOptimizer and prints a report.
 *
 * Usage:
 *   pnpm --filter @lucky-slots/engine optimize-strips
 *
 * The script defaults to the current GRID_CONFIG dimensions and uses the
 * hardcoded multipliers from constants.ts as the starting point.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { ReelOptimizer } from '../src/ReelOptimizer';
import { getMultiplier } from '../src/constants';
import { GRID_CONFIG } from '../src/config';

const __dirname = dirname(fileURLToPath(import.meta.url));

function buildBaseMultipliers(): Record<string, number> {
  const multipliers: Record<string, number> = {};
  const symbols = ['Ten', 'Jack', 'Queen', 'King', 'Ace'];
  const { minMatch, cols } = GRID_CONFIG;
  for (const sym of symbols.slice(0, GRID_CONFIG.paylineSymbols)) {
    for (let size = minMatch; size <= cols; size++) {
      multipliers[`${size} ${sym}`] = getMultiplier(size, sym);
    }
  }
  return multipliers;
}

function stripsToTypeScript(strips: string[][]): string {
  const lines: string[] = [
    '// <AUTO-GENERATED-REEL-STRIPS>',
    '// This section is automatically regenerated by `pnpm update-strips`.',
    '// Do not edit manually.',
    'export const REEL_STRIPS: string[][] = [',
  ];

  for (let r = 0; r < strips.length; r++) {
    lines.push(`  // Reel ${r + 1}`);
    lines.push('  [');
    const strip = strips[r];
    for (let i = 0; i < strip.length; i += 10) {
      const chunk = strip.slice(i, i + 10);
      const formatted = chunk.map((s) => `'${s}'`).join(',');
      const lineEnd = i + 10 >= strip.length ? '' : ',';
      lines.push(`    ${formatted}${lineEnd}`);
    }
    const comma = r < strips.length - 1 ? ',' : '';
    lines.push(`  ]${comma}`);
  }

  lines.push('];');
  lines.push('// </AUTO-GENERATED-REEL-STRIPS>');
  return lines.join('\n');
}

function parseExistingMultipliers(content: string): Record<string, number> {
  const match = content.match(/const HARDCODED_MULTIPLIERS: Record<string, number> = \{([\s\S]*?)\};/);
  if (!match) return {};
  const existing: Record<string, number> = {};
  const lines = match[1].split('\n');
  for (const line of lines) {
    const m = line.match(/^[ \t]*'([^']+)':[ \t]*([0-9.]+)/);
    if (m) {
      existing[m[1]] = parseFloat(m[2]);
    }
  }
  return existing;
}

function multipliersToTypeScript(multipliers: Record<string, number>): string {
  const entries = Object.entries(multipliers)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([k, v]) => `  '${k}': ${v.toFixed(4)},`);
  return `const HARDCODED_MULTIPLIERS: Record<string, number> = {\n${entries.join('\n')}\n};`;
}

function main() {
  const targetRTP = parseFloat(process.env.TARGET_RTP ?? '95');
  const targetHitRate = parseFloat(process.env.TARGET_HITRATE ?? '0.15');
  const iterations = parseInt(process.env.OPT_ITERATIONS ?? '100', 10);
  const spinsPerEval = parseInt(process.env.OPT_SPINS ?? '5000', 10);

  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║           Lucky Slots Reel Optimizer                         ║');
  console.log('╠══════════════════════════════════════════════════════════════╣');
  console.log(`║  Grid:       ${GRID_CONFIG.rows}×${GRID_CONFIG.cols}  (minMatch=${GRID_CONFIG.minMatch})`);
  console.log(`║  Strip size: ${GRID_CONFIG.stripSize}`);
  console.log(`║  Target RTP:       ${targetRTP.toFixed(1)}%`);
  console.log(`║  Target Hit-Rate:  ${(targetHitRate * 100).toFixed(1)}%`);
  console.log(`║  Iterations:       ${iterations}`);
  console.log(`║  Spins/eval:       ${spinsPerEval.toLocaleString()}`);
  console.log('╚══════════════════════════════════════════════════════════════╝\n');

  const baseMultipliers = buildBaseMultipliers();

  const result = ReelOptimizer.optimize({
    targetRTP,
    targetHitRate,
    baseMultipliers,
    iterations,
    spinsPerEval,
    temperature: 2.0,
    coolingRate: 0.985,
    wRtp: 1.0,
    wHit: 10.0,
    wCluster: 0.01,
    wAlign: 2.0,
    minAvgMultiplier: 3.0,
  });

  console.log(result.log.join('\n'));

  console.log('\n═══════════════════════════════════════════════════════════════');
  console.log('  OPTIMISATION RESULT');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log(`  Final RTP:        ${result.finalRTP.toFixed(2)}%`);
  console.log(`  Final Hit-Rate:   ${(result.finalHitRate * 100).toFixed(2)}%`);
  console.log(`  Final Avg Mult:   ${result.finalAvgMultiplier.toFixed(2)}x`);
  console.log('═══════════════════════════════════════════════════════════════\n');

  // Per-reel distributions
  console.log('  Per-reel symbol distributions');
  console.log('  ─────────────────────────────────────────────────────────────');
  for (let r = 0; r < result.strips.length; r++) {
    const counts: Record<string, number> = {};
    for (const s of result.strips[r]) {
      counts[s] = (counts[s] || 0) + 1;
    }
    const parts = Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .map(([s, c]) => `${s}=${c}`);
    console.log(`  Reel ${r + 1}: ${parts.join(', ')}`);
  }
  console.log('');

  // Multipliers
  console.log('  Optimised multipliers');
  console.log('  ─────────────────────────────────────────────────────────────');
  for (const [key, val] of Object.entries(result.multipliers).sort((a, b) => a[0].localeCompare(b[0]))) {
    const base = baseMultipliers[key];
    const arrow = val > base ? '↑' : val < base ? '↓' : '=';
    console.log(`  ${key.padEnd(10)} ${val.toFixed(4).padStart(10)}  (was ${base.toFixed(4)}) ${arrow}`);
  }
  console.log('');

  // Write strips to constants.ts if WRITE_CONSTANTS is set
  if (process.env.WRITE_CONSTANTS === '1') {
    const constantsPath = resolve(__dirname, '../src/constants.ts');
    let content = readFileSync(constantsPath, 'utf-8');

    // Inject REEL_STRIPS
    const stripStart = '// <AUTO-GENERATED-REEL-STRIPS>';
    const stripEnd = '// </AUTO-GENERATED-REEL-STRIPS>';
    const s0 = content.indexOf(stripStart);
    const s1 = content.indexOf(stripEnd);
    if (s0 !== -1 && s1 !== -1) {
      content = content.slice(0, s0) + stripsToTypeScript(result.strips) + content.slice(s1 + stripEnd.length);
    }

    // Inject multipliers (merge to preserve grid-size entries the optimizer didn't touch)
    const multMarker = 'const HARDCODED_MULTIPLIERS: Record<string, number> = {';
    const multEnd = '};';
    const m0 = content.indexOf(multMarker);
    if (m0 !== -1) {
      let m1 = content.indexOf(multEnd, m0);
      while (m1 !== -1 && content[m1 + 2] !== '\n' && content[m1 + 2] !== ';') {
        m1 = content.indexOf(multEnd, m1 + 1);
      }
      if (m1 !== -1) {
        const merged = { ...parseExistingMultipliers(content), ...result.multipliers };
        content = content.slice(0, m0) + multipliersToTypeScript(merged) + content.slice(m1 + 2);
      }
    }

    writeFileSync(constantsPath, content, 'utf-8');
    console.log(`  ✅  Updated ${constantsPath}`);
  } else {
    console.log('  (Set WRITE_CONSTANTS=1 to overwrite src/constants.ts)');
  }
}

main();
