#!/usr/bin/env tsx
/**
 * @fileoverview updateStrips.ts
 *
 * One-command strip regenerator.
 *
 * Usage:
 *   pnpm --filter @lucky-slots/engine update-strips
 *
 * This script:
 * 1. Reads the current GRID_CONFIG by parsing config.ts as text (no module import,
 *    so tsx cache never interferes).
 * 2. Generates new reel strips matching the RNG distribution.
 * 3. Injects them directly into src/constants.ts.
 * 4. No manual copy-paste needed.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const CONFIG_PATH = resolve(__dirname, '../src/config.ts');
const CONSTANTS_PATH = resolve(__dirname, '../src/constants.ts');

const DISTRIBUTION = [
  { symbol: 'TEN', count: 45 },
  { symbol: 'JACK', count: 10 },
  { symbol: 'QUEEN', count: 20 },
  { symbol: 'KING', count: 13 },
  { symbol: 'ACE', count: 9 },
  { symbol: 'WILD', count: 2 },
  { symbol: 'BONUS', count: 1 },
];

/** Parse config.ts as raw text — never cached, always current. */
function readConfigFromDisk(): { rows: number; cols: number; stripSize: number } {
  const content = readFileSync(CONFIG_PATH, 'utf-8');
  const rows = extractInt(content, 'rows');
  const cols = extractInt(content, 'cols');
  const stripSize = extractInt(content, 'stripSize');

  if (rows === null || cols === null || stripSize === null) {
    console.error('Failed to parse GRID_CONFIG from config.ts');
    process.exit(1);
  }

  return { rows, cols, stripSize };
}

function extractInt(content: string, key: string): number | null {
  const regex = new RegExp(`^[ \\t]*${key}:[ \\t]*(\\d+)`, 'm');
  const match = content.match(regex);
  return match ? parseInt(match[1], 10) : null;
}

function seededRandom(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 16807 + 0) % 2147483647;
    return (s - 1) / 2147483646;
  };
}

function buildStrip(seed: number, size: number): string[] {
  const rng = seededRandom(seed);
  const pool: string[] = [];
  for (const item of DISTRIBUTION) {
    for (let i = 0; i < item.count; i++) {
      pool.push(item.symbol);
    }
  }
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, size);
}

function generateStrips(reelCount: number, stripSize: number): string[][] {
  const strips: string[][] = [];
  for (let reel = 0; reel < reelCount; reel++) {
    strips.push(buildStrip(reel + 42, stripSize));
  }
  return strips;
}

function stripsToTypeScript(strips: string[][]): string {
  const lines: string[] = [
    '// <AUTO-GENERATED-REEL-STRIPS>',
    '// This section is automatically regenerated by `pnpm update-strips`.',
    '// Do not edit manually.',
    'export const REEL_STRIPS: string[][] = [',
  ];

  for (let r = 0; r < strips.length; r++) {
    lines.push(`  // Reel ${r + 1}`);
    lines.push('  [');

    const strip = strips[r];
    for (let i = 0; i < strip.length; i += 10) {
      const chunk = strip.slice(i, i + 10);
      const formatted = chunk.map((s) => `'${s}'`).join(',');
      const lineEnd = i + 10 >= strip.length ? '' : ',';
      lines.push(`    ${formatted}${lineEnd}`);
    }

    const comma = r < strips.length - 1 ? ',' : '';
    lines.push(`  ]${comma}`);
  }

  lines.push('];');
  lines.push('// </AUTO-GENERATED-REEL-STRIPS>');
  return lines.join('\n');
}

function main() {
  const { rows, cols, stripSize } = readConfigFromDisk();
  console.log(`Config: ${rows} rows × ${cols} cols, stripSize=${stripSize}`);
  console.log(`Generating ${cols} reel strips of size ${stripSize}...`);

  const strips = generateStrips(cols, stripSize);
  const generated = stripsToTypeScript(strips);

  const content = readFileSync(CONSTANTS_PATH, 'utf-8');

  const startMarker = '// <AUTO-GENERATED-REEL-STRIPS>';
  const endMarker = '// </AUTO-GENERATED-REEL-STRIPS>';

  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) {
    console.error('Could not find auto-generated markers in constants.ts');
    process.exit(1);
  }

  const before = content.slice(0, startIdx);
  const after = content.slice(endIdx + endMarker.length);
  const newContent = before + generated + after;

  writeFileSync(CONSTANTS_PATH, newContent, 'utf-8');

  console.log(`Updated ${CONSTANTS_PATH} with ${cols} reels.`);

  // Verify distribution
  let allCorrect = true;
  for (let r = 0; r < strips.length; r++) {
    const counts: Record<string, number> = {};
    for (const sym of strips[r]) {
      counts[sym] = (counts[sym] || 0) + 1;
    }
    for (const item of DISTRIBUTION) {
      if (counts[item.symbol] !== item.count) {
        console.error(`Reel ${r + 1}: ${item.symbol} expected ${item.count}, got ${counts[item.symbol]}`);
        allCorrect = false;
      }
    }
  }

  if (allCorrect) {
    console.log('All strips match the expected distribution.');
  } else {
    console.error('Distribution mismatch detected!');
    process.exit(1);
  }
}

main();
